controllers:
    resource: ../src/Controller/
    type: attribute

# Routes instrument

app_instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

instrumentLister:
    path: /gestionnaire/instrument/lister
    controller: App\Controller\InstrumentController::lister

instrumentConsulter:
    path: /gestionnaire/instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

instrumentAjouter:
    path: /gestionnaire/instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

instrumentModifier:
    path: /gestionnaire/instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier

instrumentSupprimer:
    path: /gestionnaire/instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimer

# Routes type instrument

typeInstrumentLister:
    path: /typeinstrument/lister
    controller: App\Controller\TypeInstrumentController::lister

typeInstrumentConsulter:
    path: /typeinstrument/consulter/{id}
    controller: App\Controller\TypeInstrumentController::consulter

typeInstrumentAjouter:
    path: /typeinstrument/ajouter
    controller: App\Controller\TypeInstrumentController::ajouter

typeInstrumentModifier:
    path: /typeinstrument/modifier/{id}
    controller: App\Controller\TypeInstrumentController::modifier

typeInstrumentSupprimer:
    path: /typeinstrument/supprimer/{id}
    controller: App\Controller\TypeInstrumentController::supprimer

# Routes classe instrument

classeInstrumentLister:
    path: /classeinstrument/lister
    controller: App\Controller\ClasseInstrumentController::lister

classeInstrumentConsulter:
    path: /classeinstrument/consulter/{id}
    controller: App\Controller\ClasseInstrumentController::consulter

classeInstrumentAjouter:
    path: /classeinstrument/ajouter
    controller: App\Controller\ClasseInstrumentController::ajouter

classeInstrumentModifier:
    path: /classeinstrument/modifier/{id}
    controller: App\Controller\ClasseInstrumentController::modifier

classeInstrumentSupprimer:
    path: /classeinstrument/supprimer/{id}
    controller: App\Controller\ClasseInstrumentController::supprimer

# Routes couleur

couleurLister:
    path: /couleur/lister
    controller: App\Controller\CouleurController::lister

couleurConsulter:
    path: /couleur/consulter/{id}
    controller: App\Controller\CouleurController::consulter

couleurAjouter:
    path: /couleur/ajouter
    controller: App\Controller\CouleurController::ajouter

couleurModifier:
    path: /couleur/modifier/{id}
    controller: App\Controller\CouleurController::modifier

couleurSupprimer:
    path: /couleur/supprimer/{id}
    controller: App\Controller\CouleurController::supprimer

# Routes marque

marqueLister:
    path: /marque/lister
    controller: App\Controller\MarqueController::lister

marqueConsulter:
    path: /marque/consulter/{id}
    controller: App\Controller\MarqueController::consulter

marqueAjouter:
    path: /marque/ajouter
    controller: App\Controller\MarqueController::ajouter

marqueModifier:
    path: /marque/modifier/{id}
    controller: App\Controller\MarqueController::modifier

marqueSupprimer:
    path: /marque/supprimer/{id}
    controller: App\Controller\MarqueController::supprimer

# Routes accessoire

accessoireLister:
    path: /accessoire/lister
    controller: App\Controller\AccessoireController::lister

accessoireConsulter:
    path: /accessoire/consulter/{id}
    controller: App\Controller\AccessoireController::consulter

accessoireAjouter:
    path: /accessoire/ajouter
    controller: App\Controller\AccessoireController::ajouter

accessoireModifier:
    path: /accessoire/modifier/{id}
    controller: App\Controller\AccessoireController::modifier

accessoireSupprimer:
    path: /accessoire/supprimer/{id}
    controller: App\Controller\AccessoireController::supprimer

# Routes élèves

eleveConsulter:
    path: /gestionnaire/eleve/consulter/{id}
    controller: App\Controller\eleveController::consulter

eleveLister:
    path: /gestionnaire/eleve/lister
    controller: App\Controller\eleveController::lister

eleveAjouter:
    path: /gestionnaire/eleve/ajouter
    controller: App\Controller\eleveController::ajouter

eleveModifier:
    path: /gestionnaire/eleve/modifier/{id}
    controller: App\Controller\eleveController::modifier

eleveSupprimer:
    path: /gestionnaire/eleve/supprimer/{id}
    controller: App\Controller\eleveController::supprimer


# Routes Contrats de prêt
contratPretLister:
    path: /gestionnaire/contratPret/lister
    controller: App\Controller\ContratPretController::lister

contratPretConsulter:
    path: /gestionnaire/contratPret/consulter/{id}
    controller: App\Controller\ContratPretController::consulter

contratPretAjouter:
    path: /gestionnaire/contratPret/ajouter
    controller: App\Controller\ContratPretController::ajouter

contratPretSupprimer:
    path: /gestionnaire/contratPret/supprimer/{id}
    controller: App\Controller\ContratPretController::supprimer

contratPretModifier:
    path: /gestionnaire/contratPret/modifier/{id}
    controller: App\Controller\ContratPretController::modifier

# Routes responsables

responsableConsulter:
    path: /gestionnaire/responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulter

responsableLister:
    path: /gestionnaire/responsable/lister
    controller: App\Controller\ResponsableController::lister

responsableAjouter:
    path: /gestionnaire/responsable/ajouter
    controller: App\Controller\ResponsableController::ajouter

responsableModifier:
    path: /gestionnaire/responsable/modifier/{id}
    controller: App\Controller\ResponsableController::modifier

responsableSupprimer:
    path: /gestionnaire/responsable/supprimer/{id}
    controller: App\Controller\ResponsableController::supprimer

# Route inscription

inscriptionLister:
    path: /gestionnaire/inscription/lister
    controller: App\Controller\InscriptionController::lister

inscriptionConsulter:
    path: /gestionnaire/inscription/consulter/{id}
    controller: App\Controller\InscriptionController::consulter

inscriptionAjouter:
    path: /gestionnaire/inscription/ajouter
    controller: App\Controller\InscriptionController::ajouter

inscriptionModifier:
    path: /gestionnaire/inscription/modifier/{id}
    controller: App\Controller\InscriptionController::modifier

inscriptionSupprimer:
    path: /gestionnaire/inscription/supprimer/{id}
    controller: App\Controller\InscriptionController::supprimer


confirmation_inscription:
    path: /gestionnaire/confirmation_inscription
    controller: App\Controller\ConfirmationController::confirmationInscription

# Routes cours

coursConsulter:
    path: /gestionnaire/cours/consulter/{id}
    controller: App\Controller\coursController::consulter

coursLister:
    path: /gestionnaire/cours/lister
    controller: App\Controller\coursController::lister

coursAjouter:
    path: /gestionnaire/cours/ajouter
    controller: App\Controller\coursController::ajouter

coursModifier:
    path: /gestionnaire/cours/modifier/{id}
    controller: App\Controller\coursController::modifier

coursSupprimer:
    path: /gestionnaire/cours/supprimer/{id}
    controller: App\Controller\coursController::supprimer

# Routes intervention

interventionConsulter:
    path: /gestionnaire/intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulter

# Routes générales

login:
    path: /login
    controller: App\Controller\SecurityController::login

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::accueil