controllers:
    resource: ../src/Controller/
    type: attribute
app_instrument:
    path: /instrument
    controller: App\Controller\instrumentController::index
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter