controllers:
    resource: ../src/Controller/
    type: attribute
app_instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index
app_contratPret:
    path: /contratPret
    controller: App\Controller\ContratPretController::index
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister
app_contratPretLister:
    path: /contratPret/lister
    controller: App\Controller\ContratPretController::lister
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter
app_contratPretConsulter:
    path: /contratPret/consulter/{id}
    controller: App\Controller\ContratPretController::consulter
app_contratPretAjouter:
    path: /contratPret/ajouter
    controller: App\Controller\ContratPretController::ajouter