controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_etudiant:
    path: /etudiant
    controller: App\Controller\EtudiantController::index

app_accueil:
    path: /etudiant/accueil
    controller: App\Controller\EtudiantController::accueil

etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouterEtudiant

etudiantConsulter:
    path: /etudiant/consulter/{id}
    controller: App\Controller\EtudiantController::consulter

etudiantLister:
    path: /etudiant/lister
    controller: App\Controller\EtudiantController::lister

etudiant_show:
    path: /etudiant/{id}
    controller: App\Controller\EtudiantController::show

consulterEtudiantParNomPrenom:
    path: /etudiant/consulterParNomPrenom/{nom}/{prenom}
    controller: App\Controller\EtudiantController::consulterParNomPrenom

consulterEtudiantsDateNaissSuperieur:
    path: /etudiant/consulterEtudiantsDateNaissSuperieur/{dateNaiss}
    controller: App\Controller\EtudiantController::consulterEtudiantsDateNaissSuperieur

etudiantModifier:
    path: /etudiant/modifier/{id}
    controller: App\Controller\EtudiantController::modifierEtudiant

app_maison:
    path: /maison
    controller: App\Controller\MaisonController::index

maisonConsulter:
    path: /maison/consulter/{code}
    controller: App\Controller\MaisonController::consulterMaison