controllers:
    resource: ../src/Controller/
    type: attribute

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\coursController::consulter

coursLister:
    path: /cours/lister
    controller: App\Controller\coursController::lister

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\coursController::ajouter