controllers:
    resource: ../src/Controller/
    type: attribute

# Routes instrument

app_instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister
    
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

instrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier
    
instrumentSupprimer:
    path: /instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimer

# Routes élèves

eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\eleveController::consulter

eleveLister:
    path: /eleve/lister
    controller: App\Controller\eleveController::lister

eleveAjouter:
    path: /eleve/ajouter
    controller: App\Controller\eleveController::ajouter

eleveModifier:
    path: /eleve/modifier/{id}
    controller: App\Controller\eleveController::modifier

eleveSupprimer:
    path: /eleve/supprimer/{id}
    controller: App\Controller\eleveController::supprimer

    
# Routes Contrats de prêt
contratPretLister:
    path: /contratPret/lister
    controller: App\Controller\ContratPretController::lister
    
contratPretConsulter:
    path: /contratPret/consulter/{id}
    controller: App\Controller\ContratPretController::consulter
    
contratPretAjouter:
    path: /contratPret/ajouter
    controller: App\Controller\ContratPretController::ajouter
    
contratPretSupprimer:
    path: /contratPret/supprimer/{id}
    controller: App\Controller\ContratPretController::supprimer
    
contratPretModifier:
    path: /contratPret/modifier/{id}
    controller: App\Controller\ContratPretController::modifier

# Routes responsables

responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulter

responsableLister:
    path: /responsable/lister
    controller: App\Controller\ResponsableController::lister

responsableAjouter:
    path: /responsable/ajouter
    controller: App\Controller\ResponsableController::ajouter

responsableModifier:
    path: /responsable/modifier/{id}
    controller: App\Controller\ResponsableController::modifier

responsableSupprimer:
    path: /responsable/supprimer/{id}
    controller: App\Controller\ResponsableController::supprimer

# Routes cours

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\coursController::consulter

coursLister:
    path: /cours/lister
    controller: App\Controller\coursController::lister

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\coursController::ajouter

coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\coursController::modifier

coursSupprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\coursController::supprimer