controllers:
    resource: ../src/Controller/
    type: attribute

# Routes instrument

app_instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

instrumentLister:
    path: /gestionnaire/instrument/lister
    controller: App\Controller\InstrumentController::lister

instrumentConsulter:
    path: /gestionnaire/instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

instrumentAjouter:
    path: /gestionnaire/instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

instrumentModifier:
    path: /gestionnaire/instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier

instrumentSupprimer:
    path: /gestionnaire/instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimer

# Routes élèves

eleveConsulter:
    path: /gestionnaire/eleve/consulter/{id}
    controller: App\Controller\eleveController::consulter

eleveLister:
    path: /gestionnaire/eleve/lister
    controller: App\Controller\eleveController::lister

eleveAjouter:
    path: /gestionnaire/eleve/ajouter
    controller: App\Controller\eleveController::ajouter

eleveModifier:
    path: /gestionnaire/eleve/modifier/{id}
    controller: App\Controller\eleveController::modifier

eleveSupprimer:
    path: /gestionnaire/eleve/supprimer/{id}
    controller: App\Controller\eleveController::supprimer


# Routes Contrats de prêt
contratPretLister:
    path: /gestionnaire/contratPret/lister
    controller: App\Controller\ContratPretController::lister

contratPretConsulter:
    path: /gestionnaire/contratPret/consulter/{id}
    controller: App\Controller\ContratPretController::consulter

contratPretAjouter:
    path: /gestionnaire/contratPret/ajouter
    controller: App\Controller\ContratPretController::ajouter

contratPretSupprimer:
    path: /gestionnaire/contratPret/supprimer/{id}
    controller: App\Controller\ContratPretController::supprimer

contratPretModifier:
    path: /gestionnaire/contratPret/modifier/{id}
    controller: App\Controller\ContratPretController::modifier

# Routes responsables

responsableConsulter:
    path: /gestionnaire/responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulter

responsableLister:
    path: /gestionnaire/responsable/lister
    controller: App\Controller\ResponsableController::lister

responsableAjouter:
    path: /gestionnaire/responsable/ajouter
    controller: App\Controller\ResponsableController::ajouter

responsableModifier:
    path: /gestionnaire/responsable/modifier/{id}
    controller: App\Controller\ResponsableController::modifier

responsableSupprimer:
    path: /gestionnaire/responsable/supprimer/{id}
    controller: App\Controller\ResponsableController::supprimer

# Route inscription

inscriptionLister:
    path: /gestionnaire/inscription/lister
    controller: App\Controller\InscriptionController::lister

inscriptionConsulter:
    path: /gestionnaire/inscription/consulter/{id}
    controller: App\Controller\InscriptionController::consulter

inscriptionAjouter:
    path: /gestionnaire/inscription/ajouter
    controller: App\Controller\InscriptionController::ajouter

inscriptionModifier:
    path: /gestionnaire/inscription/modifier/{id}
    controller: App\Controller\InscriptionController::modifier

inscriptionSupprimer:
    path: /gestionnaire/inscription/supprimer/{id}
    controller: App\Controller\InscriptionController::supprimer


confirmation_inscription:
    path: /gestionnaire/confirmation_inscription
    controller: App\Controller\ConfirmationController::confirmationInscription

# Routes cours

coursConsulter:
    path: /gestionnaire/cours/consulter/{id}
    controller: App\Controller\coursController::consulter

coursLister:
    path: /gestionnaire/cours/lister
    controller: App\Controller\coursController::lister

coursAjouter:
    path: /gestionnaire/cours/ajouter
    controller: App\Controller\coursController::ajouter

coursModifier:
    path: /gestionnaire/cours/modifier/{id}
    controller: App\Controller\coursController::modifier

coursSupprimer:
    path: /gestionnaire/cours/supprimer/{id}
    controller: App\Controller\coursController::supprimer

# Routes intervention

interventionConsulter:
    path: /gestionnaire/intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulter

# Routes générales

login:
    path: /login
    controller: App\Controller\SecurityController::login

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::accueil